version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_DATABASE=photoalbum"
      - "MYSQL_USER=photoalbum-user"
      - "MYSQL_PASSWORD=passkey0"
    ports:
      - "3306:3306"
  photoalbum:
    image: pluhin/photoalbum
    ports:
      - "8080:8080"